from llm_factory import get_llm
from config import DEFAULT_LLM_PROVIDER


def query_ai(conversation_history, llm_name=DEFAULT_LLM_PROVIDER) -> str:
    """
    Queries the AI model with the given conversation history.

    Args:
        conversation_history (list): A list of strings representing the conversation history.
        llm_name (str, optional): The name of the language model provider. Defaults to DEFAULT_LLM_PROVIDER.

    Returns:
        str: The response generated by the AI model.

    """

    llm = get_llm(llm_name)
    return llm.query(conversation_history)
